### ISSUE TITLE
Bug: Action incorrectly getting value from weather-api-key parameter specified in with attribute

### ISSUE THREAD

**Issue by TailonR** [bumb7ebee/weather-profile-actions#3]
I added the instructions for invoking the Github Action to my workflow, which is triggered by a workflow_dispatch. When I run the workflow it fails an error from main.py saying it can't find the key "name" in api_data_json. There is a line right above that error saying `401 Client Error: Unauthorized for url: https://api.openweathermap.org/data/2.5/weather?id=5506956&units=imperial&mod=json&appid=***%20` What this looks like to me is that a space is being appended to my api key which makes the api key incorrect and so the data being sent back isn't what the Action is expecting. 

```
- name: Get Weather using OpenWeather 
uses: bumb7ebee/weather-profile-actions@1.0.0
with:
  # OpenWeather API key
  weather-api-key: ${{ secrets.WEATHER_API_KEY }}
  # City ID obtained from OpenWeather
  city-id: ${{ github.event.inputs.city-id }}
  # Centigrade (c) or Fahrenheit (f)
  units: f
  # Country code obtained from https://flagicons.lipis.dev/
  country-code: um
  # README.md file path
  readme-path: ./weather_report.md
```

          
This is how I invoke your Action in my workflow. 

Attached is the logs associated with the error.
![Screenshot 2024-09-09 090208](https://github.com/user-attachments/assets/324247b8-06dc-4ae6-a5c4-eec82b682269)

### Steps to reproduce

1. Obtain a secret key form Open Weather and add it to your repository secrets in the Actions tab. 

2. Create a workflow in .github/workflows giving it a name. Make sure the workflow is triggered by workflow_dispatch and give it an input with the name "city-id"
```
name: Get Weather Data

on: 
  workflow_dispatch:
    inputs:
      city-id:
        required: true
        description: Enter id of a U.S city (found on openweathermap.org)
```

3. Add the instructions for invoking the workflow
```jobs:
  weather-action:
    name: Get Weather Data
    runs-on: ubuntu-latest

      - name: Get Weather using OpenWeather 
        uses: bumb7ebee/weather-profile-actions@1.0.0
        with:
          # OpenWeather API key
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
          # City ID obtained from OpenWeather
          city-id: ${{ github.event.inputs.city-id }}
          # Centigrade (c) or Fahrenheit (f)
          units: f
          # Country code obtained from https://flagicons.lipis.dev/
          country-code: um
          # README.md file path
          readme-path: ./weather_report.md
```

4. Push the code to Github and then go to the Actions tab, select the new workflow, then click the Run workflow drop down. 

5. Enter a city id and then click "run workflow"
